### ISSUE TITLE
About this gcnn

### ISSUE THREAD

**Issue by Bigrock-dd** [lorwin0130/DTIS_GCNN#1]
I'm researching dti recently, I want to use the prepared data set to input into the network, and then output the predicted ranking. Some questions I want to ask you, can you have a contact method?many thans!!!

**Comment by lorwin0130** [comment]
Sure, do you have WeChat, or any chatting software you are familiar with？

**Comment by Bigrock-dd** [comment]
> Sure, do you have WeChat, or any chatting software you are familiar with？

yes!My WeChat:Bk960926
Thanks!!
