### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by DuZhenzhen399** [lorwin0130/DTIS_GCNN#2]
你好呀，请问可以发我一份DTIS_GCNN的数据集吗？我的微信是wang399292。期待您的答复。

**Comment by lorwin0130** [comment]
你好，http://dude.docking.org/targets，这个是DUD-E数据集，里面主要是蛋白质和对应药物小分子的关联信息，这个网站里面也包含下载蛋白质的pdb文件的链接

**Comment by DuZhenzhen399** [comment]
Wow,Thank you very much.I am so glad to hear from you and I am so sorry to read this letter so late.Hope you are well.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wang ZhongXu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 中午11:50
收件人:&nbsp;"lorwin0130/DTIS_GCNN"<DTIS_GCNN@noreply.github.com&gt;;
抄送:&nbsp;"Hi,我是珍珍"<2420467594@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lorwin0130/DTIS_GCNN] Dataset (#2)





 
你好，http://dude.docking.org/targets，这个是DUD-E数据集，里面主要是蛋白质和对应药物小分子的关联信息，这个网站里面也包含下载蛋白质的pdb文件的链接
